create table if not exists la_schema_version (
  version integer not null,
  initialized_at timestamp not null
);

create table if not exists la_user (
  id varchar(64) primary key,
  username varchar(64) not null unique,
  password_hash varchar(255) not null,
  role varchar(16) not null,
  enabled boolean not null,
  created_at timestamp,
  created_by varchar(64),
  updated_at timestamp,
  last_login_at timestamp
);

create table if not exists la_namespace (
  id varchar(64) primary key,
  name varchar(64) not null unique,
  owner_id varchar(64) not null,
  description varchar(500),
  status varchar(16) not null default 'ACTIVE',
  disabled_at timestamp,
  disabled_by varchar(64),
  created_at timestamp,
  updated_at timestamp
);

create table if not exists la_topic (
  id varchar(64) primary key,
  namespace_id varchar(64) not null,
  namespace_name varchar(64),
  name varchar(64) not null,
  description varchar(500),
  owner_id varchar(64) not null,
  status varchar(16) not null,
  auth_json clob,
  inbound_format_json clob,
  templates_json clob,
  transform_json clob,
  notify_template_json clob,
  created_at timestamp,
  updated_at timestamp,
  published_at timestamp,
  unique(namespace_id, name)
);

create table if not exists la_api_key (
  id varchar(64) primary key,
  owner_id varchar(64) not null,
  name varchar(128),
  prefix varchar(32),
  key_hash varchar(128) not null,
  valid_from timestamp,
  valid_until timestamp,
  scopes_json clob,
  status varchar(16) not null,
  created_at timestamp,
  last_used_at timestamp,
  usage_count bigint not null default 0,
  rotate_count bigint not null default 0
);

create table if not exists la_notify_target (
  id varchar(64) primary key,
  user_id varchar(64) not null,
  label varchar(128),
  type varchar(32) not null,
  endpoint clob not null,
  secret clob,
  enabled boolean not null,
  created_at timestamp
);

create table if not exists la_subscription (
  topic_id varchar(64) primary key,
  contact_ids_json clob,
  updated_at timestamp
);

create table if not exists la_system_settings (
  id varchar(64) primary key,
  settings_json clob not null,
  updated_at timestamp
);

create table if not exists la_audit_log (
  id bigint generated by default as identity primary key,
  ts timestamp not null,
  type varchar(128) not null,
  actor varchar(64),
  trace_id varchar(128),
  attrs_json clob
);
